apiVersion: v1
kind: ConfigMap
metadata:
  name: welcomepage
  namespace: data-aperture
data:
  welcomepage.html: |
    <!doctype html>
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
            <title>Unauthorized</title>
            <style>
              h1 {
                margin: 2em 0;
              }
            </style>
          <script src="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.16.0/js/okta-sign-in.min.js" type="text/javascript"></script>
            <link href="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.16.0/css/okta-sign-in.min.css" type="text/css" rel="stylesheet"/>
            <link href="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.16.0/css/okta-theme.css" type="text/css" rel="stylesheet"/>
          </head>
          <body>
            <div class="container">
              <h1 class="text-center">Welcome to main cluster prod</h1>
              <div id="messageBox" class="jumbotron">
               
              </div>
            <div id="okta-login-container"></div>
            </div>
          <script type="text/javascript">
            
          </script>
          </body>
        </html>